name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "チェックアウト"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: "mise をセットアップ"
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5  # v3.5.1

      - name: "依存関係をインストール"
        run: |
          npm ci
          npx playwright install chromium --with-deps

      - name: "テスト"
        run: mise run test

      - name: "ビルド"
        run: npm run build
